name: wiring_pi_i2c
description: Dart implementation of the Wiring Pi I2C library.
version: 0.1.1
author: matzesoft

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^1.1.1
